name: Quarto Publish with Encryption

# Trigger the action whenever there is a push to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Quarto
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      # Step 3: Render the Quarto site
      - name: Render Quarto site
        run: |
          quarto render

      # Step 4: Encrypt the 'index.html' file using Staticrypt
      # This step uses the GitHub secret to pass the password securely
      - name: Encrypt index.html
        run: |
          npx staticrypt _site/index.html ${{ secrets.STATICRYPT_PASSWORD }} --short -o _site/index.html

      # Step 5: Deploy the Quarto site to the 'gh-pages' branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ITHUB_TOKEN }}
          publish_dir: ./_site

